### ISSUE TITLE
Unexpected error on City wise cluster. 

### ISSUE THREAD

**Issue by letsbuildfuture** [someshkar/covid19india-network#52] opened 2020-03-25 10:20 UTC
Unexpected error on City wise cluster.

**Comment by dhruvilmaniar** [comment] 2020-03-25 11:12
Duplicate of #42 & #41

**Comment by sibeshkar** [comment] 2020-03-25 11:29
fixed in https://github.com/someshkar/covid19india-network/pull/54

**Closed by sibeshkar** 2020-03-25 11:29 UTC
