### ISSUE TITLE
Unexpected error occured on clicking City.

### ISSUE THREAD

**Issue by aishwarya94** [someshkar/covid19india-network#42] opened 2020-03-25 06:47 UTC
![Screenshot_2020-03-25-12-15-11-10](https://user-images.githubusercontent.com/8394093/77509323-855d8280-6e92-11ea-8763-139b45be6130.png)

**Comment by vrajeshkanna** [comment] 2020-03-25 06:55
Duplicate of #41

**Comment by sibeshkar** [comment] 2020-03-25 11:30
Fixed in https://github.com/someshkar/covid19india-network/pull/54

**Closed by sibeshkar** 2020-03-25 11:30 UTC
